workspace:
  base: /workdir
  path: muxnix/
when:
  - event: push
  - event: manual
steps:
  - name: build-yocto
    image: muxelplexer/build-images
    pull: true
    volumes:
      - /etc/woodpecker/sstate-cache/:/workdir/build/sstate-cache/
    commands:
      - ./scripts/ci_build.sh
